name: GlobalBank
main: com.lenis0012.bukkit.globalbank.BankPlugin
description: Adds a unique item banking system to the game.
authors: [lenis0012, horse2950, Samkio]
dev-url: http://dev.bukkit.org/server-mods/globalbank/
version: 1.5
softdepend: [Vault]
commands:
  globalbank:
    description: GlobalBank Commands
    usage: GlobalBank Commands
    aliases: [gb]